Added node driver resource
rancher/terraform-provider-rancher2-archive pull request #16
Opened 2018-12-10 19:49 UTC by rodcloutier

Added new resource for Node Driver

2018-12-18 20:19 UTC, rawmind0 commented
Hi @rodcloutier . Thanks for the PR including node-driver.

Could you please include doc file about this resource on https://github.com/rancher/terraform-provider-rancher2/tree/master/website/docs/r folder and reference it from https://github.com/rancher/terraform-provider-rancher2/blob/master/website/rancher2.erb file??

2018-12-18 20:23 UTC, rodcloutier commented
Sure. I should have thought about this. 

> On Dec 18, 2018, at 15:19, Raúl Sánchez <notifications@github.com> wrote:
> 
> Hi @rodcloutier . Thanks for the PR including node-driver.
> 
> Could you please include doc file about this resource on https://github.com/rancher/terraform-provider-rancher2/tree/master/website/docs/r folder and reference it from https://github.com/rancher/terraform-provider-rancher2/blob/master/website/rancher2.erb file??
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-12-19 15:15 UTC, rodcloutier commented
@rawmind0 I added the documentation for the node driver resource.

2018-12-30 19:32 UTC, rawmind0 requested changes

2018-12-30 19:32 UTC, rawmind0 commented on rancher2/resource_rancher2_node_driver.go
> +		},
Could you please add `annotations` and `labels` fields??

```
+		"annotations": &schema.Schema{
+			Type:        schema.TypeMap,
+			Optional:    true,
+			Computed:    true,
+			Description: descriptions["annotations"],
+		},
+		"labels": &schema.Schema{
+			Type:        schema.TypeMap,
+			Optional:    true,
+			Computed:    true,
+			Description: descriptions["labels"],
+		},
```

2018-12-30 19:32 UTC, rawmind0 commented on rancher2/resource_rancher2_node_driver.go
> +
`annotations` and `labels` fields on flatten

```
+	err = d.Set("annotations", toMapInterface(in.Annotations))
+	if err != nil {
+		return err
+	}
+
+	err = d.Set("labels", toMapInterface(in.Labels))
+	if err != nil {
+		return err
+	}
+
```

2018-12-30 19:32 UTC, rawmind0 commented on rancher2/resource_rancher2_node_driver.go
> +	}
`annotations` and `labels` fields on expander

```
+
+	if v, ok := in.Get("annotations").(map[string]interface{}); ok && len(v) > 0 {
+		obj.Annotations = toMapString(v)
+	}
+
+	if v, ok := in.Get("labels").(map[string]interface{}); ok && len(v) > 0 {
+		obj.Labels = toMapString(v)
+	}
+
```

2018-12-30 19:32 UTC, rawmind0 commented on rancher2/resource_rancher2_node_driver.go
> +		"whitelistDomains": toArrayString(d.Get("whitelist_domains").([]interface{})),
`annotations` and `labels` fields on update

```
+		"annotations":   toMapString(d.Get("annotations").(map[string]interface{})),
+		"labels":        toMapString(d.Get("labels").(map[string]interface{})),
```

2018-12-30 19:32 UTC, rawmind0 commented on website/docs/r/nodeDriver.html.markdown
> +* `whitelist_domains` - (Optional) Domains to whitelist for the ui.
`annotations` and `labels` fields on doc

```
+* `annotations` - (Optional/Computed) Annotations of the resource (map).
+* `labels` - (Optional/Computed) Labels of the resource (map).
```

2018-12-30 19:33 UTC, rawmind0 commented
@rodcloutier thanks for adding documentation on the resource. 

Could you please take a look to the changes requested?

2019-01-03 20:30 UTC, rodcloutier commented on rancher2/resource_rancher2_node_driver.go
> +		"whitelistDomains": toArrayString(d.Get("whitelist_domains").([]interface{})),
Done

2019-01-03 20:31 UTC, rodcloutier commented
I have added the `annotations` and `labels` fields.

2019-01-03 20:57 UTC, rawmind0 approved these changes

2019-01-03 21:00 UTC, rawmind0 commented
Thanks @rodcloutier 

LGTM

2019-01-03 21:00 UTC, merged