Added openstack node template support
rancher/terraform-provider-rancher2-archive pull request #70
Opened 2019-04-04 18:47 UTC by rodcloutier

This PR intends to fix #27

2019-04-04 18:56 UTC, rodcloutier commented
The build fails but the error seems to be on master. 
`make build-rancher` passes on the branch but fails on master

2019-04-04 19:15 UTC, rawmind0 commented
Hi @rodcloutier , thanks for the PR.

build is failing to check that code complies with gofmt requirements on file 
`./rancher2/resource_rancher2_node_template.go`. Please run `make fmt` and commit updated `./rancher2/resource_rancher2_node_template.go`

2019-04-04 19:43 UTC, rodcloutier commented
I did but it is fine. Run `make fmt` on the master branch and you will get the error...
The error is here https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_node_template.go#L447

2019-04-04 20:24 UTC, rawmind0 commented
Thanks for the update. I'm going to review the PR taking it into account.

2019-04-08 15:28 UTC, rawmind0 requested changes
`ConflictsWith` is failing on execution of the provider. It seems that `ConflictsWith` is not working fine on nested structures. https://github.com/hashicorp/terraform/issues/11387, https://github.com/hashicorp/terraform/issues/11101

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"domain_name"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"domain_id"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"flavor_name"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"flavor_id"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"image_name"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"image_id"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"tenant_name"},
Please remove `ConflictsWith` definition..

2019-04-08 15:28 UTC, rawmind0 commented on rancher2/node_template_openstack_config.go
> +			ConflictsWith: []string{"tenant_id"},
Please remove `ConflictsWith` definition..

2019-04-08 15:42 UTC, rawmind0 commented
@rodcloutier , i've tested and reviewed your PR and it's not working fine. Please, take a look to changes requested. 

There are also another changes that needs to be implemented. 
- As `openstack` node driver is not activated by default on Rancher, wait for node driver activation is done is needed. 
- On `resourceRancher2NodeTemplateUpdate` function on `switch driver` openstack case is missed. I also noticed that digitalocean case was wrong and i take profit to address it.

Please, take a look to diff content on `rancher2/resource_rancher2_node_template.go`

```
diff --git a/rancher2/resource_rancher2_node_template.go b/rancher2/resource_rancher2_node_template.go
index fa03d70..37a927b 100644
--- a/rancher2/resource_rancher2_node_template.go
+++ b/rancher2/resource_rancher2_node_template.go
@@ -397,6 +397,19 @@ func resourceRancher2NodeTemplateCreate(d *schema.ResourceData, meta interface{}
                return err
        }

+       stateConf := &resource.StateChangeConf{
+               Pending:    []string{},
+               Target:     []string{"active"},
+               Refresh:    nodeDriverStateRefreshFunc(client, nodeTemplate.Driver),
+               Timeout:    d.Timeout(schema.TimeoutCreate),
+               Delay:      1 * time.Second,
+               MinTimeout: 3 * time.Second,
+       }
+       _, waitErr := stateConf.WaitForState()
+       if waitErr != nil {
+               return fmt.Errorf("[ERROR] waiting for node driver (%s) to be activated: %s", nodeTemplate.Driver, waitErr)
+       }
+
        newNodeTemplate := &NodeTemplate{}

        err = client.APIBaseClient.Create(managementClient.NodeTemplateType, nodeTemplate, newNodeTemplate)
@@ -404,7 +417,7 @@ func resourceRancher2NodeTemplateCreate(d *schema.ResourceData, meta interface{}
                return err
        }

-       stateConf := &resource.StateChangeConf{
+       stateConf = &resource.StateChangeConf{
                Pending:    []string{},
                Target:     []string{"active"},
                Refresh:    nodeTemplateStateRefreshFunc(client, newNodeTemplate.ID),
@@ -412,7 +425,7 @@ func resourceRancher2NodeTemplateCreate(d *schema.ResourceData, meta interface{}
                Delay:      1 * time.Second,
                MinTimeout: 3 * time.Second,
        }
-       _, waitErr := stateConf.WaitForState()
+       _, waitErr = stateConf.WaitForState()
        if waitErr != nil {
                return fmt.Errorf("[ERROR] waiting for node template (%s) to be created: %s", newNodeTemplate.ID, waitErr)
        }
@@ -485,7 +498,9 @@ func resourceRancher2NodeTemplateUpdate(d *schema.ResourceData, meta interface{}
        case azureConfigDriver:
                update["azureConfig"] = expandAzureConfig(d.Get("azure_config").([]interface{}))
        case digitaloceanConfigDriver:
-               update["digitaloceanConfig"] = expandAzureConfig(d.Get("digitalocean_config").([]interface{}))
+               update["digitaloceanConfig"] = expandDigitaloceanConfig(d.Get("digitalocean_config").([]interface{}))
+       case openstackConfigDriver:
+               update["openstackConfig"] = expandOpenstackConfig(d.Get("openstack_config").([]interface{}))
        }

        newNodeTemplate := &NodeTemplate{}
```

- Please add `openstack` node driver tests. Take a look to diff content on `rancher2/resource_rancher2_node_template_test.go`

```
diff --git a/rancher2/resource_rancher2_node_template_test.go b/rancher2/resource_rancher2_node_template_test.go
index 4628170..a3b6648 100644
--- a/rancher2/resource_rancher2_node_template_test.go
+++ b/rancher2/resource_rancher2_node_template_test.go
@@ -120,6 +120,52 @@ resource "rancher2_node_template" "foo" {
        access_token = "XXXXXXXXXXXXXXXXXXXX"
   }
 }
+`
+
+       testAccRancher2NodeTemplateConfigOpenstack = `
+resource "rancher2_node_template" "foo" {
+  name = "foo"
+  description = "Terraform node driver openstack acceptance test"
+  openstack_config {
+       username = "XXXXXXXXXXXXXXXXXXXX"
+       password = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+       image_name =  "image-XXXXXXXX"
+       region = "XX-west-1"
+       flavor_name = "flavor-XXXXXXXX"
+       auth_url = "http://XXXXXXXX"
+       availability_zone = "zone-XXXXXXXX"
+  }
+}
+`
+       testAccRancher2NodeTemplateUpdateConfigOpenstack = `
+resource "rancher2_node_template" "foo" {
+  name = "foo2"
+  description = "Terraform node driver openstack acceptance test - updated"
+  openstack_config {
+       username = "XXXXXXXXXXXXXXXXXXXX"
+       password = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+       image_name =  "image-YYYYYYYY"
+       region = "XX-west-1"
+       flavor_name = "flavor-XXXXXXXX"
+       auth_url = "http://XXXXXXXX"
+       availability_zone = "zone-XXXXXXXX"
+  }
+}
+ `
+       testAccRancher2NodeTemplateRecreateConfigOpenstack = `
+resource "rancher2_node_template" "foo" {
+  name = "foo"
+  description = "Terraform node driver openstack acceptance test"
+  openstack_config {
+       username = "XXXXXXXXXXXXXXXXXXXX"
+       password = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
+       image_name =  "image-XXXXXXXX"
+       region = "XX-west-1"
+       flavor_name = "flavor-XXXXXXXX"
+       auth_url = "http://XXXXXXXX"
+       availability_zone = "zone-XXXXXXXX"
+  }
+}
 `
 )

@@ -312,6 +358,69 @@ func TestAccRancher2NodeTemplate_disappears_Digitalocean(t *testing.T) {
        })
 }

+func TestAccRancher2NodeTemplate_basic_Openstack(t *testing.T) {
+       var nodeTemplate *NodeTemplate
+
+       name := testAccRancher2NodeTemplateType + ".foo"
+       resource.Test(t, resource.TestCase{
+               PreCheck:     func() { testAccPreCheck(t) },
+               Providers:    testAccProviders,
+               CheckDestroy: testAccCheckRancher2NodeTemplateDestroy,
+               Steps: []resource.TestStep{
+                       resource.TestStep{
+                               Config: testAccRancher2NodeTemplateConfigOpenstack,
+                               Check: resource.ComposeTestCheckFunc(
+                                       testAccCheckRancher2NodeTemplateExists(name, nodeTemplate),
+                                       resource.TestCheckResourceAttr(name, "name", "foo"),
+                                       resource.TestCheckResourceAttr(name, "description", "Terraform node driver openstack acceptance test"),
+                                       resource.TestCheckResourceAttr(name, "driver", openstackConfigDriver),
+                                       resource.TestCheckResourceAttr(name, "openstack_config.0.image_name", "image-XXXXXXXX"),
+                               ),
+                       },
+                       resource.TestStep{
+                               Config: testAccRancher2NodeTemplateUpdateConfigOpenstack,
+                               Check: resource.ComposeTestCheckFunc(
+                                       testAccCheckRancher2NodeTemplateExists(name, nodeTemplate),
+                                       resource.TestCheckResourceAttr(name, "name", "foo2"),
+                                       resource.TestCheckResourceAttr(name, "description", "Terraform node driver openstack acceptance test - updated"),
+                                       resource.TestCheckResourceAttr(name, "driver", openstackConfigDriver),
+                                       resource.TestCheckResourceAttr(name, "openstack_config.0.image_name", "image-YYYYYYYY"),
+                               ),
+                       },
+                       resource.TestStep{
+                               Config: testAccRancher2NodeTemplateRecreateConfigOpenstack,
+                               Check: resource.ComposeTestCheckFunc(
+                                       testAccCheckRancher2NodeTemplateExists(name, nodeTemplate),
+                                       resource.TestCheckResourceAttr(name, "name", "foo"),
+                                       resource.TestCheckReso [...]

2019-04-10 12:18 UTC, rawmind0 commented
> I did but it is fine. Run `make fmt` on the master branch and you will get the error...
> The error is here https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_node_template.go#L447
> 
> My commit actually fixes the issue. There is something weird going on...

Build checks are failing due to the golang version. Probably you have installed golang 1.11 or 1.12, but drone is using golang 1.9 for building (as detailed on README.md file).

It seems that go fmt rules have changed from golang 1.9 to 1.11 or 1.12. https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_node_template.go#L447 line is well formatted on 1.9 but wrong on 1.11 or 1.12. 

To fix it, you have 2 options: 
- remove your modification on https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/resource_rancher2_node_template.go#L447 and let the line as it was.
- Wait for merge PR #72 and rebase your PR.

2019-04-10 12:35 UTC, rawmind0 requested changes

2019-04-10 12:35 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template.go
> +		"name":                     d.Get("name").(string),
To fix build check error, please let line 447 like it was.

```
-		"name":                     d.Get("name").(string),
+		"name": d.Get("name").(string),
```

2019-05-06 15:56 UTC, rodcloutier commented
I guess I will close it in favor of #91.

I know it took a long time before I could revisit the PR but I would of liked to know that this PR was to be superseded by another work in progress...

2019-05-06 15:56 UTC, closed without merging

2019-05-06 16:05 UTC, rawmind0 commented
@rodcloutier, it wasn't a WIP, but i decided to adapt and include your PR into #91 due to long time of inactivity after review.  Thanks for your PR and sorry about that. 

Superseded by #91